### ISSUE TITLE
Vectorのテスト追加

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#12]
今の所の候補は
- cgo
- Google Test

cgo使ってみたいけど、cファイル読み込んでGoファイルにコメントで挿入してくれるツール的なのが無いときつい気がする。

**Comment by moromin** [comment]
ちょっとやってみた感じinclude のパスとかかなりめんどいすね。。。

**Comment by takumihara** [comment]
includeって読み込んでくれるんですか？

**Comment by moromin** [comment]
```go
// #cgo CFLAGS: -Iinclude
// #include "myheader.h"
import "C"
```

こんな感じで書くとヘッダーファイルとか読み込んでくれるらしいです
（まだ試してないけど。。。）

**Comment by takumihara** [comment]
なるほどです！

**Comment by takumihara** [comment]
[5/4 議論メモ]
- テスト用に全ての関数をライブラリ化し、それを読み込む
- staticの関数ってどうする？
- staticの関数は使わずに、コメントアウトで示す？笑

**Comment by moromin** [comment]
cgo使って`vec_add()`のテストやってみました。
簡単な関数なら、オブジェクトファイル＆アーカイブファイル生成とかをMakefileでうまくPATH指定してやればテストできそう？
https://gist.github.com/moromin/5d40eea61dbfc242a49da9455e143e0e

**Comment by takumihara** [comment]
確かに、ToCとかToGoとかは面倒臭いですけど、テストにヘルパー関数は付き物ですからね。
