### ISSUE TITLE
C言語でOOP！

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#14]
ここら辺役に立ちそう。
https://www.fujigoko.tv/rev/prof/doc1/index.html
https://soblin.github.io/technote/books/modern_c_programming/chapter3.html#

**Comment by takumihara** [comment]
[5/3 議論]
- 光源とカメラ以外のオブジェクトを共通化させられそう
- メソッドは、あるrayと交差するかの判定がとりあえずありそう
- 上の記事にある「仮装関数テーブルしてみたいかも」

**Comment by moromin** [comment]
さっきこれ👇見て[サンプルコード](https://gist.github.com/moromin/526fb2d18531569ebdb20d4f81880978)写経してました。
- [OOP in C](https://www.state-machine.com/doc/AN_Simple_OOP_in_C.pdf)

仮想関数テーブルやメモリのアロケーションなど、かなり丁寧に書かれてたのでおすすめです！
Notionにも貼っておきました。
