### ISSUE TITLE
明るすぎる時って処理必要？

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#20]
![スクリーンショット 2022-05-10 17 31 36](https://user-images.githubusercontent.com/69781798/167585160-27ee80d7-1bed-4401-89e0-05d30d057a84.png)
このコードで `AMBIENT_REFLECTION_COEFFICIENT` を1にしたら、前は0.01だった。
明るすぎる時の処理って何か必要？rgbを1にするとか？

**Comment by takumihara** [comment]
処理しない
![スクリーンショット 2022-05-11 0 54 34](https://user-images.githubusercontent.com/69781798/167670876-f0943718-4037-488f-8661-0d570aa9f6ed.png)

処理する
![スクリーンショット 2022-05-11 0 54 05](https://user-images.githubusercontent.com/69781798/167670799-91180ffd-77e4-483a-985f-122f91db5a42.png)

**Comment by takumihara** [comment]
@moromin これも時間ある時に確認していただけると！

**Comment by moromin** [comment]
これってmlxに渡す値がどうなると↑みたいな感じになります？

**Comment by takumihara** [comment]
今は一回intに変更してから、mlxで使う画像のbufferに入れて行っている感じです。
そもそもint挟む必要ないかもです。
1超えるとそいつ自体は、一周して黒くなって、他の色にも影響与えちゃいそうです。。。

```c
int	color_to_int(t_color color)
{
	int	rtn;

	rtn = 0;
	rtn |= (int)(color.b * 255);
	rtn |= (int)(color.g * 255) << 8;
	rtn |= (int)(color.r * 255) << 16;
	return (rtn);
}
```
```c
img->buffer[pixel + 0] = (char)(color & 0xFF);
img->buffer[pixel + 1] = (char)((color >> 8) & 0xFF);
img->buffer[pixel + 2] = (char)((color >> 16) & 0xFF);
```

**Comment by takumihara** [comment]
https://github.com/moromin/miniRT/pull/24#discussion_r869790406

**Comment by takumihara** [comment]
#61 にいたく
