### ISSUE TITLE
【質問】rayのtが複数のオブジェクトで同じ時ってどれ採用してもOK?

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#23]
doubleだから一緒になることってほぼなさそうだけど（？）

**Comment by moromin** [comment]
複数のオブジェクトで`t`が一致する＝オブジェクトが重なったところ
だと思うので、そんなに気にしなくていいと思います。

**Comment by moromin** [comment]
ただ、複数のオブジェクトの`d`が一致することは多々あると思うので、その時は、`t`が小さい方＝画面の手前にある方を優先して描画する必要があると思います。

**Comment by takumihara** [comment]
ですよね、おけです！ありがとうございます！
