### ISSUE TITLE
sliceが使いたいよ

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#25]
goみたいにappendでslice自体のアロケーション起きるとだるいので少し挙動違うけど、大体真似たもの
https://gist.github.com/8e2f291e53eace2308d34c7907466112

**Comment by moromin** [comment]
`slice`構造体の中の`cur_start`フィールドの使い道がよくわからないんですが、どう言う時に使う感じですか？
`append`, `get`でも常に`org_start`と同じところを指しているように思えるんですが、、、

**Comment by takumihara** [comment]
もう一個メソッド作る予定だったんですけど、してなくてww
```go
s[1:2]
```
みたいなことをメソッドでindex指定してやろうと思ってました。でも、今回のユースケースだとあまり使わないかも？
これ、新しいアロケーションはしないはずなので、この時の`cur_start`を進めて、 メモリの解放する時は `org_start` を使うイメージでした。
（Goの実装は `org_start` がなくて、GCの参照カウントでこれ実現しているみたいです。）

**Comment by moromin** [comment]
なるほどですw
たしかに指定したインデックス範囲のスライスを取得する処理は要らなさそうですね

**Comment by takumihara** [comment]
そうなんですよねー。ただ、sliceの本質ってそれな気がしてたりもします。これできないとC++のVecみたいな感じになる？のかと思ったり？

**Comment by takumihara** [comment]
sliceの要素をallocateされたものにするとき、解放が少し面倒くさいことが判明（多分）

https://gist.github.com/tacomeet/8e2f291e53eace2308d34c7907466112

今回の `t_object` は継承先でサイズが変わってしまうので、ポインタの配列にする必要がある。つまり、上の条件に当たってしまう。どうしようか。。。

C++とかどうやって、サイズの違う型の配列つくってるんだろうか？一番大きいやつに合わせるとか？（あれ、出来ないっけ？）

**Comment by moromin** [comment]
一番大きいオブジェクトのサイズで`make`すればいけそう・・・？
```c
size_t	max_struct_size()
{
	if (sizeof(t_sphere) > sizeof(t_plane))
		return sizeof(t_sphere);
	return sizeof(t_plane);
}

int main()
{
	slice 		*s = make(max_struct_size(), 0, 1);
	t_sphere	sp;
	t_plane		pl;

	sp.super.center = 1;
	pl.super.center = 2;
	sp.radius = 3.0;
	pl.x = 4.0;
	append(s, &sp);
	append(s, &pl);
	printf("obj1:   %f \n", ((t_object *)get(s, 0))->center);
	printf("obj2:   %f \n", ((t_object *)get(s, 1))->center);
	printf("sphere: %f \n", ((t_sphere *)get(s, 0))->radius);
	printf("plane:  %f \n", ((t_plane *)get(s, 1))->x);
	delete(s);
        
        // output
        // obj1:   1.000000 
        // obj2:   2.000000 
        // sphere: 3.000000 
        // plane:  4.000000 
}
```

**Comment by takumihara** [comment]
おおー！あざす！これって合法なんですかね

**Comment by moromin** [comment]
Cの構造体自体、フィールドの型のサイズが合わないと中で勝手に調整して余分にメモリ領域取ったりするので、合法な気がしますw

**Comment by takumihara** [comment]
なので、それをこの構造体達がしてこないとも限らないなとか思ったり？

**Comment by takumihara** [comment]
でも、構造体の配列っていうのはそもそも作れるから、どうなんですかね

**Comment by takumihara** [comment]
sliceのsliceにするとこんなことになるww
ああー、マクロ使いてー
```
t_object *obj = get(*(t_slice **)get(program.object, 0), 0);
```

**Comment by takumihara** [comment]
でもとりあえず動いたっぽい

**Comment by takumihara** [comment]
https://www.sejuku.net/blog/25556

共用体が使えるかも？
