### ISSUE TITLE
入力ファイルのバリデーション

### ISSUE THREAD

**Issue by moromin** [moromin/miniRT#3]
- miniRTでは、入力として`*.rt`形式のファイルが引数として渡される。
- そのファイルの中身含めて、バリデーションを行う。

**Comment by moromin** [comment]
`char *`->`double`への変換を行うための関数`strtod`のサンプル
https://gist.github.com/e328a31fdefdeded7ff19224ded627c1

**Comment by takumihara** [comment]
https://github.com/tacomeet/fractal/blob/master/simple_atof.c
一応僕もfract-olの時に作りました！

**Comment by takumihara** [comment]
@moromin 何かまだありますか？

**Comment by moromin** [comment]
subjectの要件は満たしてるっぽいので大丈夫だと思います
