### ISSUE TITLE
表記割れをどこかのタイミングで直したい

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#31]

**Comment by takumihara** [comment]
posとcoordinate

**Comment by moromin** [comment]
`t_object`の場合、`t_vector center`のようにどのような座標か、という情報を変数名に持たせている。
なので、`t_light`, `t_camera`とかも`t_vector pos`みたいに座標の情報を持たせた方がいいと思います。

**Comment by takumihara** [comment]
賛成です！
