### ISSUE TITLE
rtファイルをコメントアウトに対応させたい！

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#32]
課題的にありかな...

**Comment by moromin** [comment]
`load_element`の中とかで、自分たちは`#`をコメント識別子として処理することにしました
ってことにすれば問題ないと思います。
レビュワー次第ですが

**Comment by takumihara** [comment]
自分もありだと思います！

**Comment by takumihara** [comment]
closed by https://github.com/moromin/miniRT/pull/35
