### ISSUE TITLE
[BONUS]鏡面反射光

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#34]
```
• Add specular reflection to have a full Phong reflection model.
```
これってすでに実装しているやつだけで良いのだろうか？
それとも、完全鏡面反射もやる？
https://knzw.tech/raytracing/?page_id=1577

**Comment by takumihara** [comment]
@moromin 

鏡面反射係数の受け取り方

- rmatsukaさん達は、materialっていう項目を追加していた。多分、直前のオブジェクトに情報を追加しているのだと考えられる
- せっかく、オブジェクトごとにパース関数を作っているので、 `sp`とかのオブジェクトの末尾に追加できる風にしても良いかと思う。設定されていなかったら、デフォルト値を使うみたいな。

**Comment by moromin** [comment]
オブジェクトの末尾に追加する方が、`rt`ファイルの見通しが良くなると思うのでそっちで行きたいですね。

**Comment by takumihara** [comment]
ですね！変更しておきまーす！

**Comment by takumihara** [comment]
あと、思い出したんですけど、必要な要素がない時と、逆に多い時のエラー判定もtodoですよね？

**Comment by moromin** [comment]
です

**Comment by takumihara** [comment]
> Phongの反射モデルでは、...
このモデルは、「局所的な」反射モデルである。すなわち、ラジオシティのようなレイトレーシングで行うような二次反射を計算する必要はない。

https://ja.wikipedia.org/wiki/Phong%E3%81%AE%E5%8F%8D%E5%B0%84%E3%83%A2%E3%83%87%E3%83%AB


やっぱり、完全鏡面反射は入らないみたい

**Comment by takumihara** [comment]
とりまclose
