### ISSUE TITLE
ohkuboさんテストケースバグ

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#40]
https://github.com/kohkubo/minirt_sample

- [x] 1, 2-…, 8-..., 11-... -> 鏡面反射が違う？
- [x] 6-2 -> わからん
- [x] 6-… -> 円柱の影が逆？
- [x] 8-… -> cameraのFOVが全部行っちゃってる
- [x] 10 -> わからん
- [x] 11->オブジェクトの中にいる時、描画が全くされない
- [x] 11 ->オブジェクトの中にいる時、影が描画されない
- [ ] 12 -> 途中
- [ ] 13-0 -> 薄くて見えん
- [x] 13-1 -> わからん
- [x] 13-2 -> わからん

**Comment by takumihara** [comment]
> 8-… -> cameraのFOVが全部行っちゃってる

```C     0,1000,0    0,-1,0      102```
こんな感じで、視線の方向が ey(0,1,0)と並行の時に、dxを求める外積が0になっちゃって、描画に失敗している

**Comment by moromin** [comment]
> 6-… -> 円柱の影が逆？

円柱の法線ベクトルの計算が多分間違ってる。
視線ベクトルPを元に計算するのではなく、ライトのベクトルを元に計算しないといけない説あります。
PR出した時の描画がいい感じだったのはカメラとライトがほぼ同じ位置にあったから？

**Comment by takumihara** [comment]
> 8-… -> cameraのFOVが全部行っちゃってる


> 視線dfとeyが並行ってことは、真上か真下から見るケースだと思うので、その場合だけdx = exにするといけるかもですね

これで解決！光度が少し違うけど、1,2と一緒で鏡面反射・環境光の定数の問題かと！

**Comment by takumihara** [comment]
> 視線ベクトルPを元に計算するのではなく、ライトのベクトルを元に計算しないといけない説あります。

なるほどです！僕もオブジェクトの中とか、平面を裏から見てるときに対応しようとしているんですけど、交差点だけじゃ法線ベクトル求められない気がしますね

光の計算するときに必要なのは、視線方向への交差点の法線ベクトル（？）

**Comment by takumihara** [comment]
> 法線ベクトルとは、ある直線に垂直なベクトル、または、ある平面に垂直なベクトルのことで、𝑛⃗  と表します。
法線で重要なのはその向き（= 直線または面に垂直であること）だけなので、法線ベクトル 𝑛⃗  は無数に存在します（法線方向を向いていれば大きさはなんでもOK）。

https://univ-juken.com/hosen#i-5

`calc_normal()` にカメラの位置を渡すのは違って、受け取り側で内積との±を見て、-1かけるべき（？）

**Comment by takumihara** [comment]
> calc_normal() にカメラの位置を渡すのは違って、受け取り側で内積との±を見て、-1かけるべき（？）

カメラから交差点へのベクトルとの内積を取って、一応判定できてそう

https://github.com/moromin/miniRT/pull/43

**Comment by takumihara** [comment]
>  11 ->オブジェクトの中にいる時、影が描画されない

シンプルに条件が間違ってた...
#44

**Comment by takumihara** [comment]
>  1, 2-…, 8-..., 11-... -> 鏡面反射が違う？
 10 -> わからん


#45 
鏡面反射係数のデフォルト値設定と計算の修正で解決したはず！

**Comment by takumihara** [comment]
>  6-2 -> わからん

これも鏡面反射の問題だったみたい！
#45

**Comment by takumihara** [comment]
>  13-1 -> わからん
 13-2 -> わからん

#46 

> オブジェクトに厚みが無い？と考え、微小な値をスクリーン方向にプラスすることで解決。（ユーザー体験的にも、カメラを移動できるとして、オブジェクトに重なるときに一瞬全て同じ色になるのは微妙そう）

**Comment by moromin** [comment]
>  6-… -> 円柱の影が逆？

#49 

`cylinder`のレイ方程式を求めるメソッドの修正と`EPSILON`定数の調整により解決！

**Comment by takumihara** [comment]
多分大丈夫でしょう！
