### ISSUE TITLE
[BONUS]スポットライト

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#47]
rmatsukaさんのrtファイル

```
sl [x,y,z coordinates] [direction] [fov] [ratio] [R,G,B colors in range [0-255]] 
sl  5,-0.2,5            -1,0,0      45    1       50,250,50
```

**Comment by takumihara** [comment]
```
- **sl スポットライト**
    - 非実体
    - `sl vector unit_vetor fov_angle ratio color`
        - 頂点位置
        - 中心軸方向
        - 開き角(度)
        - 輝度比
        - 色ベクトル
```

**Comment by takumihara** [comment]
ベクトルの計算はこれでいける？

![miniRT-14](https://user-images.githubusercontent.com/69781798/168409278-c63eb724-fba0-48ac-b948-9836861936e9.jpg)


要素的には、`t_light`と被ってるから継承して、`t_spotlight`を作る。
物体の交差点から光源までのベクトルをとって、それが範囲内かを返すメソッドを作る？普通の光源の場合は絶対に `true` 
このメソッドが light が持つべきものなのかが難しい。。。

**Comment by moromin** [comment]
いいと思います！
`t_light`を継承した`t_spotlight`をつくる場合、`handle_lights`をひきすうとかいじってメソッドにする感じですかね？

**Comment by takumihara** [comment]
`handle_lights()` はlightでループを回していて、どっちみちその処理は必要になるので、`handle_lights()` の中から呼べるメソッドを作ろうかなと思ってました！
`is_reachable` みたいな？

**Comment by takumihara** [comment]
> 逆体位ベクトル

単位です。ごめんなさい。。。www

**Comment by moromin** [comment]
www

**Comment by takumihara** [comment]
とりあえず完了？ #54
