### ISSUE TITLE
[BONUS] バンプマップ

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#48]
バンプマップとは
- [バンプマッピング - Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%90%E3%83%B3%E3%83%97%E3%83%9E%E3%83%83%E3%83%94%E3%83%B3%E3%82%B0)

GIMPっていう無料のソフトウェアで作れそう
- [GIMP 思い込み～日本一詳しいバンプマップの使用方法～ - YouTube](https://www.youtube.com/watch?v=PHzpjue0Yhg)

描画の仕方
- [床井研究室 - 第２４回 バンプマッピング](https://marina.sys.wakayama-u.ac.jp/~tokoi/?date=20050826)
- [wgld.org | WebGL: バンプマッピング |](https://wgld.org/d/webgl/w042.html)

**Comment by takumihara** [comment]
めちゃめちゃ嘘w

> [GIMP 思い込み～日本一詳しいバンプマップの使用方法～ - YouTube](https://www.youtube.com/watch?v=PHzpjue0Yhg)

バンプマップ作るんじゃなくて、バンプマップから実際の画像を作ってるわ


> [wgld.org | WebGL: バンプマッピング |](https://wgld.org/d/webgl/w042.html)

バンプマッピングだけど、高さマップじゃなくて、法線マップ使ってるわ

**Comment by takumihara** [comment]
https://tangrams.github.io/heightmapper/

世界地図のハイトマップ作れるサイト？

**Comment by takumihara** [comment]
[Bitmap2Materialの使い方#3：Height Map、Normal Mapの作り方 - CGrad Project](https://www.cgradproject.com/archives/2368/)

**Comment by takumihara** [comment]
kawadaさんnotion読み終わった。むずい

**Comment by moromin** [comment]
加えてこらへんのサイトも視覚的にわかりやすかった気がする
- [法線マップと接空間](https://esprog.hatenablog.com/entry/2016/05/01/025634)
- [Tutorial 13 : Normal Mapping](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-13-normal-mapping/)

**Comment by takumihara** [comment]
@moromin こいつも？

**Comment by moromin** [comment]
これも実装したんで閉じやす！
