### ISSUE TITLE
[BONUS] 球、平面、円筒以外の物体

### ISSUE THREAD

**Issue by moromin** [moromin/miniRT#51]
subjectにあった物体のリスト
- `Cone` : 円錐
- `Hyperboloid` : 双曲面
- `Paraboloid` : 放物面

**Comment by takumihara** [comment]
円錐は乗ってる
https://knzw.tech/raytracing/?page_id=1621

**Comment by moromin** [comment]
一応, yokawadaさんのnotionでもベクトル方程式と法線ベクトルを計算してくれていた。

**Comment by moromin** [comment]
メモ
![スクリーンショット 2022-05-14 15 33 45](https://user-images.githubusercontent.com/34294957/168414037-65a56f86-0f1f-4e34-8097-2b8873b10fa9.png)

**Comment by moromin** [comment]
法線ベクトルの計算、yokawadaさんのやつって逆じゃない？

**Comment by takumihara** [comment]
![スクリーンショット 2022-05-14 18 21 11](https://user-images.githubusercontent.com/69781798/168419616-2fd53e0c-49b8-42bb-bd4d-088ee8eded16.png)

これって最初に、両辺二乗してるからですよね？cos -> cos ^ 2

**Comment by moromin** [comment]
その式は、交差点が円錐の方向ベクトルと同じ方向にあるか、逆の方向にあるかを判定しているものなので、cosはあんまり関係ないかも・・・？

**Comment by takumihara** [comment]
そういう意味だと、そもそもfovが180未満ってチェックしておけば、等式が満たされないかなって思ったんですよね。ただ、計算の過程で両辺二乗してるからその情報が消えたのかと思ったり？

元々の式ってこれで、このcosの値ってfov180越えなければ、正ですよね

![スクリーンショット 2022-05-14 18 30 03](https://user-images.githubusercontent.com/69781798/168419985-0b7be32a-1b30-4343-9cb8-14e2e3f63911.png)

**Comment by moromin** [comment]
こんな感じのイメージですね
![スクリーンショット 2022-05-14 18 31 20](https://user-images.githubusercontent.com/34294957/168420039-934316f5-a7c1-4a64-94ed-dee1b3f922b9.png)

**Comment by takumihara** [comment]
そしたら、この付加条件は、dirの方向に伸びてる円錐だけを描画する時に必要ってことですか？

**Comment by moromin** [comment]
です！
dirと同じ・逆の両方向に伸びた円錐を描画したい場合は、この条件はいらないと思います。

**Comment by moromin** [comment]
> 元々の式ってこれで、このcosの値ってfov180越えなければ、正ですよね

そう言う意味では、元々の式はdirの方向と交差点が同じ方向にあると仮定してcosを計算しているのだと思います。

**Comment by takumihara** [comment]
あーなるほどです！ありがとうございます！

**Comment by takumihara** [comment]
> 法線ベクトルの計算、yokawadaさんのやつって逆じゃない？

どっちの方向でも法線ベクトルなんだと思います！
https://univ-juken.com/hosen#i-5
![スクリーンショット 2022-05-14 18 43 07](https://user-images.githubusercontent.com/69781798/168420425-764cd5ae-02e4-4e31-b255-befce6c17f88.png)


我々もどっち向きの法線ベクトルが来ても、radiance求めるところで、視線の方向に向いてる法線ベクトルを採用するので、どっちでも大丈夫だと思います！

**Comment by moromin** [comment]
たしかに！あざす！

**Comment by takumihara** [comment]
法線ベクトル求めるところって、kawadaさんのnotionむず過ぎるんですけど、幾何学的考察って↓であってますか？（下半分のやつです。）なんか、`norm(p - c) * cos(theta/2)` のところが無理矢理な感じもするのですが,,,ww

![miniRT-16](https://user-images.githubusercontent.com/69781798/168420661-4631d145-806d-4813-b419-70137594cfd0.jpg)

**Comment by moromin** [comment]
僕も同じ考えでやりました！
最後の式は、(p-c)cos(θ/2) - dしたものを正規化する感じですね

**Comment by takumihara** [comment]
> 最後の式

これは↓のコードを指してますか？
```c
res = vec_normalize(vec_sub(vec_mult(center_to_cross, cos(me->aperture / 2 / 180 * M_PI)), direction));
```

**Comment by moromin** [comment]
まさにそうです！

**Comment by takumihara** [comment]
了解です！ありがとうございます！

**Comment by takumihara** [comment]
@moromin これも？

**Comment by moromin** [comment]
ｳｪｲ!
