### ISSUE TITLE
[BONUS]チェッカーボード

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#53]

**Comment by takumihara** [comment]
チェッカーボードのやり方について書いてそう
[Texture Mapping](http://www.raytracerchallenge.com/bonus/texture-mapping.html)

**Comment by takumihara** [comment]
[疑問]
チェッカーボードの色はどの値を変えれば良いのだろうか？

現状、objectのパラメタで渡される `color` を拡散反射係数として解釈していた。
ただ、rmatsukaさんたちは、この `color` とは別に拡散反射係数を指定できるようにしていた


自分の今までの理解だと、メインの色は拡散反射係数で決定されるから、objectの`color`をどう使えばいいのか分からない。

また、チェッカーボードで指定された色はこの拡散反射係数を変更してしまえば良いのだろうか？

**Comment by takumihara** [comment]
@moromin 
［相談］円柱のチェッカーの描画方法

前提:
チェッカー柄を-1から1までをとる、u, vの二次元で持っておく。
3次元（x, y, z）を二次元に変換し、そのタイミングでの色を取り出すことで、綺麗なチェッカーになる。


例:(次にあげるPRの参考にして頂ければ！)
平面は、法線ベクトルに直行する基底ベクトル2つを用意し、描画したい平面上の点（我々の変数ではcross point）が、基底ベクトル何個分かを求め、その少数部分をu, vにする。

球は、方位角と仰角を求め、それを-1から1に変換し、u,vにする。
※球の半径と方位角と仰角があれば、その点を一意に特定できる（中心が原点からずれるのではあれば、その分だけずらす）

本題:
円柱もハサミで切ればほぼ平面なので、それを採用したい。
中心が(0,0,0)で軸が(0,1,0)の円柱を考える（半径と高さは適当に）
縦に関しては、交差点と軸の内積を取り、それを高さで割ればu またはvが取れる（質問1）
横に関しては、この円柱でいう（1,0,0）と(0,1,0)のような基底ベクトルが欲しい。軸と（軸に並行では無い）適当なベクトルの外積を基底ベクトル1に。この基底ベクトル1と軸の外積を基底ベクトル2に出来る（質問2）
この基底ベクトル1,2と交差点の内積をそれぞれ取り、atan2を取れば、方位角が求まり、これがIまたはvになる。（質問3）

どうでしょうか？

**Comment by moromin** [comment]
質問１：いいと思います。u, vの範囲を-1 ~ 1にするのであれば、内積を高さで割るだけだと0~1の範囲になってしまいそうなので、そこの計算をちょっといじらないといけないかな？と思いました。

質問２：軸と並行でない適当なベクトルということは、`center_to_cross`のようなベクトルでもいいと思ったので図にしてみたのですが、基底ベクトルのイメージってこれであってますか？
![スクリーンショット 2022-05-15 14 06 48](https://user-images.githubusercontent.com/34294957/168458128-30748279-7467-409c-a9b5-1c79cde347f3.png)

質問３：基底ベクトルから方位角を求めるところがちょっと理解できなかったので、図かなにかあるとありがたいです。

**Comment by takumihara** [comment]
ありがとうございます！

> チェッカー柄を-1から1までをとる、u, vの二次元

0~1でした笑


> 基底ベクトルのイメージってこれであってますか？

あってます！ありがとうございます！
ただ、この基底ベクトルはプログラムを通して同じ値を持っておくもので（これがuvの2次元の幅と高さになる）、交差点が無い状態で求めたいかもです。


> 質問３：基底ベクトルから方位角を求めるところがちょっと理解できなかったので、図かなにかあるとありがたいです。

PRの方で書きます！（頑張りますww）
