### ISSUE TITLE
TODOリスト（リファクタリング・新機能等）

### ISSUE THREAD

**Issue by moromin** [moromin/miniRT#61]
- [x] `vec_inner_product()` -> `vec_dot()`など関数名変更。
- [x] 物体ににおける基本的な反射係数は`t_material`、チェッカーボードやバンプマップなどの付加情報は`t_additional`, `t_supplement`など適当な構造体に格納するようにする。
- [x] テクスチャマッピング（BONUS) [moromin]
- [x] 完全鏡面反射（BONUS）
- [x] READMEにクラス図追加
- ~~Norm対応~~ (別ISSUE)
- [x] colorの誤差無くす
- [x] uvがマイナスの時（平面と円錐）
- [x] calc_normal() の処理をradianceを求めるときだけ、bumpmapを考慮するように変更 [moromin]
- [ ]  coneの先っちょに交差したとき、法線ベクトルがゼロベクトルになる？　[moromin]
- [x]  flagの比較は&とる
- [x]  u, v揃える [moromin]
- [x] e1, e2などの基底ベクトルの事前計算 [tacomeet]
- [x]  カメラの位置などの事前計算 [tacomeet]
- [x]  u, vを求める関数を作る [ tacomeet]
- [x] 光の係数を統一化 [tacomeet]
- [x] `ch_color_at()`に変更[tacomeet]
- [x] calc_radiance()をメソッドではなくする[tacomeet]
- [x] cylinderの`calc_uv()`を左上を(0,0)にする[tacomeet]
- [ ]

**Comment by takumihara** [comment]
- [x] `calc_normal()` の処理をradianceを求めるときだけ、bumpmapを考慮するように変更 [moromin]

**Comment by takumihara** [comment]
- [ ] coneの先っちょに交差したとき、法線ベクトルがゼロベクトルになる？

**Comment by takumihara** [comment]
- [x] flagの比較は&とる
- [x] u, v揃える [moromin]

**Comment by moromin** [comment]
- [x] e1, e2などの基底ベクトルの事前計算 [tacomeet]

**Comment by takumihara** [comment]
- [x] カメラの位置などの事前計算 [tacomeet]

**Comment by takumihara** [comment]
- [x] u, vを求める関数を作る [ tacomeet]

**Comment by takumihara** [comment]
- [x] 光の係数を統一化 [tacomeet]

**Comment by takumihara** [comment]
@moromin 
>  coneの先っちょに交差したとき、法線ベクトルがゼロベクトルになる？　[moromin]

これって？

**Comment by moromin** [comment]
> @moromin
> 
> > coneの先っちょに交差したとき、法線ベクトルがゼロベクトルになる？　[moromin]
> 
> これって？

[カワダさんのNotion](https://cooperative-nutmeg-ef9.notion.site/e368390af0d3461991a76fe85b994bd6#57520e770600408b92e07acb24b7658d)の計算式を元に法線ベクトルを計算すると、円錐の先端にレイが交差した時、法線ベクトルがゼロになるんですよね。
それで、法線ベクトルがゼロの時、どこかでゼロ除算的なエラー出るかもな〜と思って一応書いてました。

今のところ円錐を描画するときに特にエラー出てないので、一応大丈夫だとは思います。。。

**Comment by takumihara** [comment]
done!
