### ISSUE TITLE
ウィンドウ最小化した時

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#75]
`mlx_expose_hook()` 使うっぽい

**Comment by takumihara** [comment]
任せましたwwww

**Comment by moromin** [comment]
一応メモ：so_longの時は、`mlx_loop_hook()`で再描画してたっぽいww

**Comment by takumihara** [comment]
> 一応メモ：so_longの時は、`mlx_loop_hook()`で再描画してたっぽいww

それは良くないやつですよww

**Comment by moromin** [comment]
ですよねww
