### ISSUE TITLE
課題提出前チェック

### ISSUE THREAD

**Issue by takumihara** [moromin/miniRT#82]
- [x] 関数の確認
- [ ] サンプルの確認
- [ ] norm

**Comment by moromin** [comment]
担当`rt`ファイル
## moromin
### mandatory
- [x] cylinder
- [x] cone
- [x] proj_3-1
- [x] err_lack_identifier
- [x] err_duplicate_identifier
- [x] err_plane_range
### bonus
- [x] texture
- [x] bumpmap
- [x] err_invalid_file_path
- [x] err_real_overflow

## tacomeet
### mandatory
- [x] ambient_lighting
- [x] camera
- [x] plane
- [x] err_plane_range2
- [x] err_sphere_range
- [x] err_light_range
### bonus
- [x] ch_multi
- [x] sl_basic
- [x] err_ch_multi
- [x] err_real_invalid
