### ISSUE TITLE
ソースファイルのディレクトリ構成

### ISSUE THREAD

**Issue by moromin** [moromin/miniRT#9]
今回、miniRT自体の処理を書くソースファイルがそんなに多くはならないと思う。
しかし、minishellの`wrapper`, `utils`などのディレクトリに入っていた関数を使いたい場面が今後出てくるはず。
なので、そのディレクトリとヘッダーファイルをどこに置くべきか議論したい。

**Comment by moromin** [comment]
個人的には、`wrapper`, `utils`に含まれる関数はminiRTに（exitの処理以外）依存しない汎用的なものなので、`src`ディレクトリ以下ではなく、rootディレクトリに直接置くのがいいと思う。
ヘッダーも、`include`ではなくその追加したディレクトリ以下の方がわかりやすいと思う。

**Comment by takumihara** [comment]
`lib` ディレクトリを作るのもありですかね？
rootディレクトリ下でも良いと思います！

**Comment by moromin** [comment]
これも大体方向性決まったのでClose！
